name: Generate Resume PDF

on:
  push:
    branches:
      - master  # Trigger on pushes to the master branch
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: macos-latest

    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4.2.2

      - name: Set up Pandoc and wkhtmltopdf engine
        run: |
          brew install pandoc
          brew install wkhtmltopdf

      - name: Getting tools versions
        run: |
          pandoc --version
          wkhtmltopdf --version

      - name: Run compile script
        run: |
          cd Resume
          . ./compile.sh

      - name: Set and create Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "TAG_NAME=v$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_ENV
          git remote -v
          git tag ${{ env.TAG_NAME }}
          git push origin ${{ env.TAG_NAME }}

      - name: Release artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: "./Resume/Henry Nguyen's resume.pdf"
          tag_name: ${{ env.TAG_NAME }}
          token: ${{ secrets.GITHUB_TOKEN }}