name: Generate Resume PDF

on:
  push:
    branches:
      - master  # Trigger on pushes to the master branch
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4.2.2

      - name: Set up Pandoc and wkhtmltopdf engine
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc
          sudo apt-get install -y wkhtmltopdf

      - name: Run compile script
        run: |
          sudo pandoc "Henry Nguyen's resume.md" -o "Henry Nguyen's resume.pdf" \
            --metadata title="Henry Nguyen's resume" \
            --css=style.css \
            --pdf-engine=wkhtmltopdf \
            --pdf-engine-opt="--enable-local-file-access" \
            --variable margin-top=30pt \
            --variable margin-left=30pt \
            --variable margin-right=30pt \
            --variable margin-bottom=30pt \
            --variable pagestyle=empty

      - name: Upload Resume PDF
        uses: actions/upload-artifact@v4.4.3
        with:
          name: resume-pdf
          path: "./Henry Nguyen's resume.pdf"  # Adjust this to match the output file name
