name: Generate Resume PDF

on:
  push:
    branches:
      - master  # Trigger on pushes to the master branch
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4.2.2

      - name: Set up Pandoc and wkhtmltopdf engine
        run: |
          sudo apt-get update
          sudo apt-get install wget
          wget https://github.com/jgm/pandoc/releases/download/3.5/pandoc-3.5-1-amd64.deb
          sudo dpkg -i pandoc-3.5-1-amd64.deb
          sudo apt-get install -y wkhtmltopdf

      - name: Getting tools versions
        run: |
          pandoc --version
          wkhtmltopdf --version

      - name: Run compile script
        run: ./Resume/compile.sh

      - name: Upload PDF of the resume
        uses: actions/upload-artifact@v4.4.3
        with:
          name: resume-pdf
          path: "Resume/Henry Nguyen's resume.pdf"
