name: Generate Resume PDF

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Pandoc and wkhtmltopdf
        run: |
          brew install pandoc
          brew install wkhtmltopdf

      - name: Run compile script
        run: ./compile.sh

      - name: Upload Resume PDF
        uses: actions/upload-artifact@v2
        with:
          name: resume-pdf
          path: "./Henry Nguyen's CV.pdf"  # Adjust this to match the output file name
