name: Generate Resume PDF

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4.2.2

      - name: Set up Pandoc and wkhtmltopdf engine
        run: |
          brew install pandoc
          brew install wkhtmltopdf

      - name: Debugging
        run: |
          pwd
          ls

      - name: Run compile script
        run: |
          pandoc "Henry Nguyen's resume.md" -o "Henry Nguyen's resume.pdf" \
            --css="resume_style.css" \
            --pdf-engine=wkhtmltopdf \
            --variable margin-top=30pt \
            --variable margin-left=30pt \
            --variable margin-right=30pt \
            --variable margin-bottom=30pt \
            --variable pagestyle=empty

      - name: Upload Resume PDF
        uses: actions/upload-artifact@v4.4.3
        with:
          name: resume-pdf
          path: "./Henry Nguyen's CV.pdf"  # Adjust this to match the output file name
